apiVersion: v1
kind: Service
metadata:
  name: go-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: gin
  ports:
    - port: 5050
      targetPort: 5050
status:
  loadBalancer:
    ingress:
    - ip: 0.0.0.0
